### ISSUE TITLE
ShouldBeLike causes out-of-memory errors if two objects hold mutual references

### ISSUE THREAD

**Issue by NameOfTheDragon** [machine/machine.specifications.should#10]
I was implementing a directed graph object `Node` where a node has an `IEnumerable<Node> Connections` property. I created a two node graph where `NodeA` links to `NodeB` and `NodeB` links to `NodeA`. I put these node instance into a `List<Node>` and pass that to my unit under test (A Dijkstra shortest path algorithm). This returns an `IEnumerable<Node>` representingthe shortest path. Clearly, the shortest path from A to B in a 2 node graph is AB, and that's my expected result. I looks like this:

    public class when_computing_the_path_between_two_nodes_with_a_single_route
        {
        Establish context = () =>
            {
            nodeA = new Node("A");
            nodeB = new Node("B");
            nodeA.ConnectsTo(nodeB);
            var graph = new List<INode> {nodeA, nodeB};
            router = new DijkstraRouteFinder(graph);
            };
        Because of = () => route = router.FindRoute(nodeA, nodeB);
        It should_find_the_single_route = () => route.ShouldBeLike(new List<INode> {nodeA, nodeB});
        static DijkstraRouteFinder router;
        static Node nodeA;
        static Node nodeB;
        static IEnumerable<INode> route;
        }

When this context executes, Visual Studio immediately freezes. If lucky, after some time the test will terminate with an `OutOfMemoryException`, but typically the machine starts thrashing o badly that it's impossible to take any corrective action (on one occasion it took me almost an hour to regain enough control to open task manager and kill Visual Studio).

The problem isn't in the route finder because it isn't implemented yet! It actually just returns a 2-node graph that is hard coded.

Data structures with circular references are not that uncommon and it seems like `ShouldBeLike` should be smart enough to detect this and stop descending the object graph if it has seen the object before.

I am afraid I don't have the bandwidth at the moment to take this issue on myself, here it is if anyone wants to have a go, otherwise I may pick it up in a few months when I have more time.

**Comment by drauch** [comment]
Closed with pull request https://github.com/machine/machine.specifications.should/pull/14
