### ISSUE TITLE
ShouldBeLikeInternal's visited cache problem

### ISSUE THREAD

**Issue by drauch** [machine/machine.specifications.should#17]
The following assertion should throw, but does not:

    // a and b are sample DTOs of the same type with different property values
    new [] { a, b } .ShouldBeLike( new [] { a, a } );

The problem seems to be that object `a` is already marked `visited` by `ShouldBeLikeInternal`'s visited cache and therefore not re-evaluated.

**Comment by drauch** [comment]
Repro solution: https://www.dropbox.com/s/q0484zux29ar937/ShouldBeLikeArrayRepro.zip?dl=0

**Comment by drauch** [comment]
Pull request: https://github.com/machine/machine.specifications.should/pull/18

**Comment by ivanz** [comment]
Closing based on the pull request being merged.
