### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by penderi** [machine/machine.specifications.should#21]
Hi,
I'm trying to create a PR that adds custom messages to Excceptions. I've pulled the repo but when I try and run the tests I see:

"Provided spec assembly path is not a propert path.
Parameter name: >\bin\*.dll"

I'm using R# mspec runner and VS 2015 update 4.

I'm wondering if the repo has a problem or it's an issue with my local env ...

**Comment by ivanz** [comment]
Sorry - I must have missed this one whilst on holiday. ReSharper support for running tests in "dotnet cli" projects is coming in the next version. you can run the tests on the command line via `dotnet test`
